spring:
  redis:
    database: 5  # Redis数据库索引（默认为0
    # host: 192.168.3.150 # Redis服务器地址
    host: 127.0.0.1
    port: 6379  # Redis服务器连接端口
    pool:
      max-active: 200 # 连接池最大连接数（使用负值表示没有限制）
      max-idle: 50 # 连接池中的最大空闲连接
      max-wait: 15000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
      min-idle: 1 # 连接池中的最小空闲连接